USE [master]
GO
/****** Object:  Database [PedidosDb]    Script Date: 15/01/2026 10:58:23 ******/
CREATE DATABASE [PedidosDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PedidosDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\PedidosDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PedidosDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\PedidosDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [PedidosDb] SET COMPATIBILITY_LEVEL = 170
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PedidosDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PedidosDb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PedidosDb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PedidosDb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PedidosDb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PedidosDb] SET ARITHABORT OFF 
GO
ALTER DATABASE [PedidosDb] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [PedidosDb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PedidosDb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PedidosDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PedidosDb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PedidosDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PedidosDb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PedidosDb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PedidosDb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PedidosDb] SET  ENABLE_BROKER 
GO
ALTER DATABASE [PedidosDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PedidosDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PedidosDb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PedidosDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PedidosDb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PedidosDb] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [PedidosDb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PedidosDb] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [PedidosDb] SET  MULTI_USER 
GO
ALTER DATABASE [PedidosDb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PedidosDb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PedidosDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PedidosDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PedidosDb] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [PedidosDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [PedidosDb] SET OPTIMIZED_LOCKING = OFF 
GO
ALTER DATABASE [PedidosDb] SET QUERY_STORE = ON
GO
ALTER DATABASE [PedidosDb] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [PedidosDb]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 15/01/2026 10:58:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Pedido]    Script Date: 15/01/2026 10:58:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Pedido](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[NumeroPedido] [nvarchar](50) NOT NULL,
	[Cliente] [nvarchar](200) NOT NULL,
	[Fecha] [datetime2](7) NOT NULL,
	[Total] [decimal](18, 2) NOT NULL,
	[Estado] [char](1) NOT NULL,
 CONSTRAINT [PK_Pedido] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Usuario]    Script Date: 15/01/2026 10:58:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuario](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Email] [nvarchar](max) NOT NULL,
	[Password] [nvarchar](max) NOT NULL,
	[Rol] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Usuario] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_Pedido_NumeroPedido]    Script Date: 15/01/2026 10:58:24 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_Pedido_NumeroPedido] ON [dbo].[Pedido]
(
	[NumeroPedido] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Pedido] ADD  DEFAULT ('R') FOR [Estado]
GO
USE [master]
GO
ALTER DATABASE [PedidosDb] SET  READ_WRITE 
GO
